### ISSUE TITLE
Научно-исследовательская часть

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#10]
**2.	Научно-исследовательская часть**

**2.1.	 Постановка задачи проектирования**
	Задачами проектирования являются:
1.	Спроектировать модель базы данных.
2.	Разработать клиентскую часть приложения.
3.	Разработать бизнес-логику приложения.
4.	Разработать серверную часть приложения.
5.	Оформить документацию.

**2.2.	Описание предметной области**
Футбольный клуб – это коллектив, который играет в футбол в турнирах со своим названием, эмблемой. Коллектив - состав команды. Они же играют в турнирах. Для отслеживания игр необходимо расписание матчей.
Каждый футбольный клуб имеет историю основания. Так же клуб достигает определённых успехов в турнирах.
Если человек хочет подержать команду или ему понравилась их форма, то у него появится желание приобрести эту форму, и для этого нужен магазин футбольного клуба.
Все эти элементы нужно перенести на сайт, чтобы вся нужная информация была расположена на сайте этого клуба. 

**2.3.	Анализ аналогов и прототипов**

При проектировании сайта были взяты некоторые идеи и интересные дизайнерские подходы с других подобных сайтов.
Основные пункты футбольных сайтов, без которых сложно представить подобного рода сайт:
 1.	Расписание игр
 2.	Состав
 3.	Текущее положение в турнире
 4.	Достижения
 Остальные пункты не особо важны для интересующегося футболом человека, такие как:
 1.	История основания
 2.	Магазин

Обосновывается это тем, что никому не интересна история основания, кроме болельщиков команды. В магазин первый попавшиеся интернет пользователь не зайдёт и не станет покупать продукт, если только форма не привлечёт его своим дизайном.
 
Данные элементы были взяты за основу разработки визуальной части некоторых страниц:
1. Некоторые категории для навигации сайта у ФК Калуги. Клуб, Матчи, Магазин. https://fc-kaluga.ru/
 
![image](https://user-images.githubusercontent.com/106113300/192161310-ecff4253-e7c8-4178-b72c-798f3915bbab.png)
Рисунок 2.1 – навигация сайта ФК Калуга

2. Внешний вид состава у Реал Мадрида, так как был прост в реализации. https://www.realmadrid.com/en/football/squad

![image](https://user-images.githubusercontent.com/106113300/192161316-201b3a5d-fdc1-4779-9404-dadd628a0ad5.png)
Рисунок 2.2 – Список игроков команды у Real Madrid
 
3. Расписание/результаты игр у ФК Барселоны, так как прост в реализации и привлекателен с дизайнерской точки зрения. https://www.fcbarcelona.com/en/football/first-team/results
 
![image](https://user-images.githubusercontent.com/106113300/192161321-149122be-82f8-4ddd-9343-bc84007665ce.png)
Рисунок 2.3 – список сыгранных матчей FC Barcelona

4. Внешний вид для магазина -  у Манчестера Сити. Также прост в реализации, как и состав команды (та же механика работает по расположению элементов). https://shop.mancity.com/en/kits/#tile-701221522-black
 
![image](https://user-images.githubusercontent.com/106113300/192161328-a144be9c-ecd1-441c-83e0-7f79c6f2c44c.png)
Рисунок 2.4 – список товаров в магазине Manchester City

Также планируется доработать покупку в таком же стиле как у Сити.
https://shop.mancity.com/en/manchester-city-away-jersey-2022-23/701221522-black.html
 
![image](https://user-images.githubusercontent.com/106113300/192161332-7af343fd-1a2e-4b98-b4e4-c794e0f335bc.png)
Рисунок 2.5 – страница покупки товара в магазине Manchester City

Остальные аспекты либо были реализованы самостоятельно такие, как турнирная таблица, главная страница. Либо ещё будут реализованы – история основания и достижения.

**2.4.	Перечень задач, подлежащих решению в процессе разработки**
	Перечень задач:
●	Описать предметную область.
●	Проанализировать аналоги.
●	Спроектировать концептуальную модель предметной области.
●	Спроектировать логическую модель.
●	Выбрать инструменты для разработки клиентской части и бизнес-логику.
●	Изучить выбранные инструменты.
●	Разработать клиентскую часть.
●	Разработать бизнес-логику.
●	Разработка северной части.
●	В процессе разработки проекта оформить документацию к нему.

**2.5.	 Концептуальная схема данных**
 
![image](https://user-images.githubusercontent.com/106113300/204305182-e0c3ae3c-9f6f-4c84-a977-e11e37496c4c.png)
Схема 2.1 – концептуальная схема БД

Турниры и Турнирные таблицы зависят друг к другу связью «Один ко многим», так как турнир проводится не 1 раз, а несколько раз за свою историю существования (конечно, бывают исключения). Например, есть Английская Премьер-Лига и её проводят с Лета по Весну (этот период называется сезон), а когда начинается следующий сезон, то турнир, по сути, тот же самый (Логотип, название), но другой, с точки зрения времени.
Турниры таблицы и Игровые дни зависят друг к другу двумя связями «Один ко многим», так как турнира будет формироваться из результатов матчей. Если турнир только начался и игры ещё не сыгранны, то за счёт расписания будущих игр будет формироваться турнирная таблица.
Участники и Игровые дни зависят друг к другу двумя связями «Один ко многим», так как игровые дни формируются из участников, которые между собой играют, и они будут встречаться несколько раз в разных игровых днях. Атрибут у Участников «Наша ли команда?» необходима для вывода на сайте расписание с результатами игр исключительна для нашей команды.

**2.6.	 Требования к приложению**
Система должна соответствовать следующим требованиям:
1.	Поддержка функции авторизации
2.	Адекватное отображение всех страниц на всех устройствах
3.	Хранение данных об сыгранных играх, таблиц прошедших турниров, мерча в магазине.
4.	Покупка и доставка товара
Первый пункт необходим для покупки мерча и на перспективу. При регистрации от пользователя требуется e-mail и пароль. E-mail будет необходим для оплаты и доставки с помощью СДЭК. В будущем, если наш клуб будет расти и будут на горизонте появляться спонсоры, то число зарегистрированных пользователей могут нам помочь в получении денежных средств за счёт рекламы их продукции.
Второй пункт необходим для отображения сайта на всех устройствах, в частности, на мобильных устройствах компьютеров.
Третий пункт связан с хранением информации в БД. Для этого необходимо написать код, который будет связывать БД с шаблоном сайта.
Четвёртый пункт связан с оформлением заказа покупателя. Покупатель выбирает себе товар, вводит номер телефона для того, чтобы мы в ближайшее время связались с ним и обговорили об доставке (адрес для доставки СДЭКа) с последующей оплатой.

**Comment by wldmr-key** [comment]
норм
