### ISSUE TITLE
Физическая схема данных

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#11]
--
-- PostgreSQL database dump
--

-- Started on 2022-11-29 20:41:09

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);

ALTER TABLE public.auth_group OWNER TO postgres;

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.auth_group_permissions OWNER TO postgres;

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    codename character varying(100) NOT NULL,
    content_type_id integer NOT NULL
);

ALTER TABLE public.auth_permission OWNER TO postgres;

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."auth_user_user_permissions""" (
);

ALTER TABLE public."auth_user_user_permissions""" OWNER TO postgres;

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);

ALTER TABLE public.django_admin_log OWNER TO postgres;

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);

ALTER TABLE public.django_content_type OWNER TO postgres;

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);

ALTER TABLE public.django_migrations OWNER TO postgres;

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

ALTER TABLE public.django_session OWNER TO postgres;

CREATE TABLE public.main_matches (
    id bigint NOT NULL,
    date date NOT NULL,
    stage character varying(30) NOT NULL,
    home_goals numeric(3,0),
    away_goals numeric(3,0),
    away_team_id bigint,
    home_team_id bigint,
    table_id bigint DEFAULT 3,
    link_vk character varying(100)
);

ALTER TABLE public.main_matches OWNER TO postgres;

ALTER TABLE public.main_matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.main_members (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    logo character varying(100) DEFAULT 'main/img/MembersAE/NoLogo.png'::character varying NOT NULL,
    q_we boolean DEFAULT false NOT NULL
);

ALTER TABLE public.main_members OWNER TO postgres;

ALTER TABLE public.main_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.main_players (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    number smallint NOT NULL,
    photo character varying(100),
    link_vk character varying(100),
    CONSTRAINT main_players_number_check CHECK ((number >= 0))
);

ALTER TABLE public.main_players OWNER TO postgres;

ALTER TABLE public.main_players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_players_id_seq
    START WITH 12
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.main_tables (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date,
    update_date date,
    tournament_id bigint
);

ALTER TABLE public.main_tables OWNER TO postgres;

ALTER TABLE public.main_tables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_tables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.main_tournaments (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    photo character varying(100) NOT NULL
);

ALTER TABLE public.main_tournaments OWNER TO postgres;

ALTER TABLE public.main_tournaments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_tournaments_id_seq
    START WITH 2
    INCREMENT BY 1
    MINVALUE 2
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_account (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);

ALTER TABLE public.shop_account OWNER TO postgres;

CREATE TABLE public.shop_account_groups (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    group_id integer NOT NULL
);

ALTER TABLE public.shop_account_groups OWNER TO postgres;

ALTER TABLE public.shop_account_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_account_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.shop_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_account_user_permissions (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.shop_account_user_permissions OWNER TO postgres;

ALTER TABLE public.shop_account_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_account_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_kinds (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);

ALTER TABLE public.shop_kinds OWNER TO postgres;

ALTER TABLE public.shop_kinds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_kinds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_orders (
    id bigint NOT NULL,
    "dataTime" timestamp with time zone,
    phone_number character varying(16),
    sum_price numeric(10,2),
    account_id bigint,
    status boolean
);

ALTER TABLE public.shop_orders OWNER TO postgres;

ALTER TABLE public.shop_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_products (
    id bigint NOT NULL,
    slug character varying(50) NOT NULL,
    year date NOT NULL,
    photo character varying(100) NOT NULL,
    price numeric(7,2) NOT NULL,
    kind_id bigint,
    cat_id bigint
);

ALTER TABLE public.shop_products OWNER TO postgres;

ALTER TABLE public.shop_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shop_purchases (
    id bigint NOT NULL,
    size character varying(4) NOT NULL,
    quantity smallint NOT NULL,
    order_id bigint,
    product_id bigint,
    CONSTRAINT shop_purchases_quantity_b60a2443_check CHECK ((quantity >= 0))
);

ALTER TABLE public.shop_purchases OWNER TO postgres;

ALTER TABLE public.shop_purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."shop_сategories" (
    id bigint NOT NULL,
    name character varying(25) NOT NULL,
    slug character varying(50) NOT NULL
);

ALTER TABLE public."shop_сategories" OWNER TO postgres;

ALTER TABLE public."shop_сategories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."shop_сategories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE VIEW public.table_tournaments AS
 WITH games AS (
         SELECT DISTINCT me.name,
            count(*) AS count_games,
            ma.table_id,
            me.q_we
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE (((ma.home_team_id = me.id) OR (ma.away_team_id = me.id)) AND (tab.id = ma.table_id))
          GROUP BY me.name, ma.table_id, me.q_we
        ), wins AS (
         SELECT DISTINCT me.name,
            count(*) AS count_wins,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE (((ma.home_team_id = me.id) AND (ma.home_goals > ma.away_goals) AND (tab.id = ma.table_id)) OR ((ma.away_team_id = me.id) AND (ma.home_goals < ma.away_goals) AND (tab.id = ma.table_id)))
          GROUP BY me.name, ma.table_id
        ), draws AS (
         SELECT DISTINCT me.name,
            count(*) AS count_draws,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE (((ma.home_team_id = me.id) AND (ma.home_goals = ma.away_goals) AND (tab.id = ma.table_id)) OR ((ma.away_team_id = me.id) AND (ma.home_goals = ma.away_goals) AND (tab.id = ma.table_id)))
          GROUP BY me.name, ma.table_id
        ), loses AS (
         SELECT DISTINCT me.name,
            count(*) AS count_loses,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE (((ma.home_team_id = me.id) AND (ma.home_goals < ma.away_goals) AND (tab.id = ma.table_id)) OR ((ma.away_team_id = me.id) AND (ma.home_goals > ma.away_goals) AND (tab.id = ma.table_id)))
          GROUP BY me.name, ma.table_id
        ), goal_for_home AS (
         SELECT DISTINCT me.name,
            sum(ma.home_goals) AS count_goal_for_h,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE ((ma.home_team_id = me.id) AND (tab.id = ma.table_id))
          GROUP BY me.name, ma.table_id
        ), goal_for_away AS (
         SELECT DISTINCT me.name,
            sum(ma.away_goals) AS count_goal_for_a,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE ((ma.away_team_id = me.id) AND (tab.id = ma.table_id))
          GROUP BY me.name, ma.table_id
        ), goal_against_home AS (
         SELECT DISTINCT me.name,
            sum(ma.away_goals) AS count_goal_against_h,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE ((ma.home_team_id = me.id) AND (tab.id = ma.table_id))
          GROUP BY me.name, ma.table_id
        ), goal_against_away AS (
         SELECT DISTINCT me.name,
            sum(ma.home_goals) AS count_goal_against_a,
            ma.table_id
           FROM public.main_members me,
            public.main_matches ma,
            public.main_tables tab
          WHERE ((ma.away_team_id = me.id) AND (tab.id = ma.table_id))
          GROUP BY me.name, ma.table_id
        )
 SELECT DISTINCT row_number() OVER () AS id,
    g.name,
    g.count_games,
    COALESCE(w.count_wins, (0)::bigint) AS wins,
    COALESCE(d.count_draws, (0)::bigint) AS draws,
    COALESCE(l.count_loses, (0)::bigint) AS loses,
    (COALESCE(gfh.count_goal_for_h, (0)::numeric) + COALESCE(gfa.count_goal_for_a, (0)::numeric)) AS goal_for,
    (COALESCE(gah.count_goal_against_h, (0)::numeric) + COALESCE(gaa.count_goal_against_a, (0)::numeric)) AS goal_against,
    ((COALESCE(gfh.count_goal_for_h, (0)::numeric) + COALESCE(gfa.count_goal_for_a, (0)::numeric)) - (COALESCE(gah.count_goal_against_h, (0)::numeric) + COALESCE(gaa.count_goal_against_a, (0)::numeric))) AS goal_difference,
    ((COALESCE(w.count_wins, (0)::bigint) * 3) + COALESCE(d.count_draws, (0)::bigint)) AS pts,
    g.table_id,
    g.q_we
   FROM (((((((games g
     LEFT JOIN wins w USING (name, table_id))
     LEFT JOIN draws d USING (name, table_id))
     LEFT JOIN loses l USING (name, table_id))
     LEFT JOIN goal_for_home gfh USING (name, table_id))
     LEFT JOIN goal_for_away gfa USING (name, table_id))
     LEFT JOIN goal_against_home gah USING (name, table_id))
     LEFT JOIN goal_against_away gaa USING (name, table_id))
  ORDER BY g.table_id, ((COALESCE(w.count_wins, (0)::bigint) * 3) + COALESCE(d.count_draws, (0)::bigint)) DESC, ((COALESCE(gfh.count_goal_for_h, (0)::numeric) + COALESCE(gfa.count_goal_for_a, (0)::numeric)) - (COALESCE(gah.count_goal_against_h, (0)::numeric) + COALESCE(gaa.count_goal_against_a, (0)::numeric))) DESC;

ALTER TABLE public.table_tournaments OWNER TO postgres;

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);

ALTER TABLE ONLY public.main_matches
    ADD CONSTRAINT main_matches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.main_members
    ADD CONSTRAINT main_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.main_players
    ADD CONSTRAINT main_players_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.main_tables
    ADD CONSTRAINT main_tables_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.main_tournaments
    ADD CONSTRAINT main_tournaments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_account
    ADD CONSTRAINT shop_account_email_key UNIQUE (email);

ALTER TABLE ONLY public.shop_account_groups
    ADD CONSTRAINT shop_account_groups_account_id_group_id_542895f9_uniq UNIQUE (account_id, group_id);

ALTER TABLE ONLY public.shop_account_groups
    ADD CONSTRAINT shop_account_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_account
    ADD CONSTRAINT shop_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_account_user_permissions
    ADD CONSTRAINT shop_account_user_permis_account_id_permission_id_a1a4188f_uniq UNIQUE (account_id, permission_id);

ALTER TABLE ONLY public.shop_account_user_permissions
    ADD CONSTRAINT shop_account_user_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_kinds
    ADD CONSTRAINT shop_kinds_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_orders
    ADD CONSTRAINT shop_orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT shop_products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT shop_products_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.shop_purchases
    ADD CONSTRAINT shop_purchases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public."shop_сategories"
    ADD CONSTRAINT "shop_сategories_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public."shop_сategories"
    ADD CONSTRAINT "shop_сategories_slug_key" UNIQUE (slug);

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

CREATE INDEX main_matches_away_team_id_49ef9896 ON public.main_matches USING btree (away_team_id);

CREATE INDEX main_matches_home_team_id_b57c4bef ON public.main_matches USING btree (home_team_id);

CREATE INDEX main_matches_table_id_478ffc81 ON public.main_matches USING btree (table_id);

CREATE INDEX main_tables_tournament_id_9800f07d ON public.main_tables USING btree (tournament_id);

CREATE INDEX shop_account_email_648c3f12_like ON public.shop_account USING btree (email varchar_pattern_ops);

CREATE INDEX shop_account_groups_account_id_ce6d1c33 ON public.shop_account_groups USING btree (account_id);

CREATE INDEX shop_account_groups_group_id_e279f7d4 ON public.shop_account_groups USING btree (group_id);

CREATE INDEX shop_account_user_permissions_account_id_a918caec ON public.shop_account_user_permissions USING btree (account_id);

CREATE INDEX shop_account_user_permissions_permission_id_b54c9313 ON public.shop_account_user_permissions USING btree (permission_id);

CREATE INDEX shop_orders_account_id_957ce53b ON public.shop_orders USING btree (account_id);

CREATE INDEX shop_products_cat_id_e10b7b4f ON public.shop_products USING btree (cat_id);

CREATE INDEX shop_products_kind_id_7bf7dd7a ON public.shop_products USING btree (kind_id);

CREATE INDEX shop_products_slug_364ff7dd_like ON public.shop_products USING btree (slug varchar_pattern_ops);

CREATE INDEX shop_purchases_order_id_7309c2ce ON public.shop_purchases USING btree (order_id);

CREATE INDEX shop_purchases_product_id_909aeb58 ON public.shop_purchases USING btree (product_id);

CREATE INDEX "shop_сategories_slug_fc461657_like" ON public."shop_сategories" USING btree (slug varchar_pattern_ops);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_shop_account_id FOREIGN KEY (user_id) REFERENCES public.shop_account(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.main_matches
    ADD CONSTRAINT main_matches_away_team_id_49ef9896_fk_main_members_id FOREIGN KEY (away_team_id) REFERENCES public.main_members(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.main_matches
    ADD CONSTRAINT main_matches_home_team_id_b57c4bef_fk_main_members_id FOREIGN KEY (home_team_id) REFERENCES public.main_members(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.main_matches
    ADD CONSTRAINT main_matches_table_id_478ffc81_fk_main_tables_id FOREIGN KEY (table_id) REFERENCES public.main_tables(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.main_tables
    ADD CONSTRAINT main_tables_tournament_id_9800f07d_fk_main_tournaments_id FOREIGN KEY (tournament_id) REFERENCES public.main_tournaments(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_account_groups
    ADD CONSTRAINT shop_account_groups_account_id_ce6d1c33_fk_shop_account_id FOREIGN KEY (account_id) REFERENCES public.shop_account(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_account_groups
    ADD CONSTRAINT shop_account_groups_group_id_e279f7d4_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_account_user_permissions
    ADD CONSTRAINT shop_account_user_pe_account_id_a918caec_fk_shop_acco FOREIGN KEY (account_id) REFERENCES public.shop_account(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_account_user_permissions
    ADD CONSTRAINT shop_account_user_pe_permission_id_b54c9313_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_orders
    ADD CONSTRAINT shop_orders_account_id_957ce53b_fk_shop_account_id FOREIGN KEY (account_id) REFERENCES public.shop_account(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT "shop_products_cat_id_e10b7b4f_fk_shop_сategories_id" FOREIGN KEY (cat_id) REFERENCES public."shop_сategories"(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_products
    ADD CONSTRAINT shop_products_kind_id_7bf7dd7a_fk_shop_kinds_id FOREIGN KEY (kind_id) REFERENCES public.shop_kinds(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_purchases
    ADD CONSTRAINT shop_purchases_order_id_7309c2ce_fk_shop_orders_id FOREIGN KEY (order_id) REFERENCES public.shop_orders(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.shop_purchases
    ADD CONSTRAINT shop_purchases_product_id_909aeb58_fk_shop_products_id FOREIGN KEY (product_id) REFERENCES public.shop_products(id) DEFERRABLE INITIALLY DEFERRED;

-- Completed on 2022-11-29 20:41:10

--
-- PostgreSQL database dump complete
--

**Comment by wldmr-key** [comment]
все норм. Для читаемости я бы убрал служебные комментарии и сгруппировал все по таблицам, но это необязательно. Надеюсь, ты, по-прежнему, готов отвечать за каждое слово в своей работе ;)
например DEFERRABLE INITIALLY DEFERRED )

**Comment by JohnBlec** [comment]
А не легче тогда уже сделать физ. схему из блоков схем?)

Тогда и опасных вопросов не будет)

**Comment by wldmr-key** [comment]
будут-будут

**Comment by JohnBlec** [comment]
Я тут начал переносить физ. схему в приложение и получается в 28 страниц))
С учётом шрифта в 10 и Courier New
Что с этим делать? Неужели печатать все эти страницы...

**Comment by wldmr-key** [comment]
для начала убрать комментарии. Ну, может, верстку изменить. А, потом, принять волевое решение, что дороже - сберечь енмного природы или принять ритуальные условности (мое предположение - тебе пятерку и без приложения поставят)
