### ISSUE TITLE
Проектно-конструкторская часть

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#12]
1.	Проектно-конструкторская часть

1.1.	 Реализация готового приложения.
	Для решения задач, описанных выше и создания приложения, обладающего всеми вышеперечисленными функциями, необходимо решить, как будут применяться для решения задач СУБД Postgres, какие таблицы будут использоваться, и Python Django. Так же для упрощения структуры будет полезно разбить проект на приложения: main и shop.

1.2.	Разработка и реализация структуры базы данных

Для реализации структуры базы данных была разработана его логическая схема. Данная схема приведена ниже:

![image](https://user-images.githubusercontent.com/106113300/205509714-f6fd2928-8221-4f39-99e1-ca74e0389fe3.png)
Схема 3.1 – Логическая схема БД

Все таблицы были реализованы с помощью Django. Подробнее об этом будет написано в следующем разделе.
Так же было создано представление (view) для отрисовки строк в турнирных таблицах. Так как турнирная таблица берёт данные из таблицы с матчами, то есть представляет собой агрегирование по результатам матчей. Поэтому, целесообразно её реализовать в форме представления. Django, в свою очередь, будет обращаться к нему как к таблице, но с ограниченным доступом на модификацию. Привязка представления к Django расписан также в следующем разделе.

Запрос, который создаёт данную таблицу, расположена в Приложении 1 Запрос 1. Краткий анализ данного запроса:
Запрос состоит из 2-х частей: описание вспомогательных запросов WITH и основного запроса, который связывает вспомогательные запросы. В первой части описаны 8 запросов по выявлению данных из результатов матчей с помощью агрегатов COUNT и SUM: количество сыгранных игр, побед, ничьих, поражений, забитых дома голов, забитых в гостях голов, пропущенных дома голов, пропущенных в гостях голов. Во второй части соединяются данные 8 запросов с помощью LEFT JOIN, так как не все таблицы имели полноценную информацию. Например, есть команда, которая все матчи победила, ни разу не сыграв в ничью и не проиграв, она не будет отображаться в запросах с количеством ничьих и поражений, так как эти данные отсутствуют. После привязки таблиц описываем выводимые данные из них. В столбцах с каким-либо числом в качестве данных, кроме количества игр и id таблиц, для корректного подсчёта и отображения информации использовалась COALESCE. Данная функция фильтровала значения из строк. Например, если в столбце с победами (wins) параметр w.count_wins будет NULL, то вместо NULL будет подставляться 0. Также для корректного отображения позиций в турнирной позиции команд использовалась сортировка ORDER BY.

Хоть и запрос работает корректно, но имеет недостаток. Недостатком является маленькая производительность, так как у данного запроса есть 8 вспомогательных запроса, каждая из которых по отдельности проходит полный цикл по всем матчем, что сказывается на производительности. Поэтому необходимо разработать решение, в котором запросу представления приходилось минимальное количество раз проходить цикл по всем матчам. И решение данной задачи расположена в Приложении 1 Запрос 2. В данном запросе каждый столбец с подсчётом количества чего-либо использовались CASE, который при обходе данных о матчах рассматривал все возможные варианты и совершал подсчёты в зависимости выполнения определённых условий. В остальном запрос ничем не отличается от предыдущего запроса.

На основе этих данных были сформированы базы данных. Физическая схема БД расположена в Приложении 1 Структура 1.

1.3.	 Разработка структуры приложения
	Создание таблиц в Django реализуется с помощью моделей в model.py, то есть описание таблицы. Описание таблицы включает себя: название таблицы, названия столбцов, описание типов данных столбцов. Пример описания таблиц приведён ниже:

```
class Tables(models.Model):
    start_date = models.DateField('Начало турнира')
    end_date = models.DateField('Окончание турнира', null=True)
    tournament = models.ForeignKey('Tournaments', on_delete=models.CASCADE, verbose_name="Турнир")
    update_date = models.DateField('Обновление данных таблицы', null=True)
```

Данный класс имеет следующие элементы:
•	У класса присутствует 1 параметр, который отвечает за указание того, что данный класс является моделью для таблицы.
•	 Описание столбцов таблицы. Они в свою очередь имеют следующие параметры:
o	Наименование столбца для админки Django
o	null=True – может ли в данном столбце находится значение Null
o	Для внешнего ключа необходимы такие параметры, как название модели (класса), к которому необходимо привязать данную модель, и указать инструкцию. Инструкция срабатывает тогда, когда экземпляр из таблицы Tournaments удалили, а поле tournament отсылался на данный экземпляр. При model.CASCADE все экземпляры таблицы Tables, которые ссылались на удалённый экземпляр класса Tournaments, удаляться. Также есть и инструкция model.SET_NULL, который в свою очередь вместо удаления экземпляров в поле tournament установится значение Null, но тогда понадобиться дополнительный параметр для ForeignKey - null=True.

Чтобы модели появились в качестве таблиц в Postgres необходимо совершить миграции. При их завершении Django автоматически создаст столбец с id к каждой таблице.
	Для того, чтобы к существующей таблице в Postgres сделать модель и привязать его, то необходимо добавить к модели класс Meta и присвоить к полю db_table имя таблицы из БД.
Если рассматривать данный проект, то примером может послужить представление (view) из Postgres table_tournaments. Его описание приведено ниже: 

```
class TablesView(models.Model):
    id = models.PositiveBigIntegerField(primary_key=True)
    name = models.CharField('Название команды', max_length=50)
    count_games = models.DecimalField('Игры', max_digits=2, decimal_places=0)
    wins = models.DecimalField('Победы', max_digits=2, decimal_places=0)
    draws = models.DecimalField('Ничьи', max_digits=2, decimal_places=0)
    loses = models.DecimalField('Поражения', max_digits=2, decimal_places=0)
    goal_for = models.DecimalField('Забитые голы', max_digits=3, decimal_places=0)
    goal_against = models.DecimalField('Пропущенные голы', max_digits=3, decimal_places=0)
    goal_difference = models.DecimalField('Разница мячей', max_digits=3, decimal_places=0)
    pts = models.DecimalField('Очки', max_digits=3, decimal_places=0)
    table = models.ForeignKey('Tables', on_delete=models.CASCADE)
    q_we = models.BooleanField('Наша ли команда?', default=False)

    class Meta:
        managed = False
        db_table = 'table_tournaments'
```

Так как данные для представления заполняются с помощью запроса в Postgres, то нужно убрать возможность модифицировать данные в этой таблице с помощью поля managed=False.

1.4	 Разработка алгоритмов обработки информации
	Основной задачей сайта, работающей с базами данных, является запись данных в таблицы и вывод данных из таблиц.
	Примером записи данных в таблицу послужит отправка товара в корзину. Алгоритм записи данных приведён ниже:

```
def buy(request, product_slug, user_id):
    product = get_object_or_404(Products, slug=product_slug)
    if request.method == 'POST':
        form = CartAddPurchasesForm(request.POST)
        if form.is_valid():
            if Account.objects.filter(pk=user_id):
                account = Account.objects.get(pk=user_id)
                if Orders.objects.filter(account_id=user_id, status=False):
                    ords = Orders.objects.get(account_id=user_id, status=False)
                    p = Purchases()
                    p.product = product
                    p.quantity = request.POST['quantity']
                    p.size = request.POST['size']
                    p.order = ords
                    p.save()
                    return redirect('cart', user_id)              
		else:
                    o = ord_creat(account)
                    p = Purchases()
                    p.product = product
                    p.quantity = request.POST['quantity']
                    p.size = request.POST['size']
                    p.order = o
                    p.save()
                    return redirect('cart', user_id)
            else:
                return redirect('singIn')

    form = CartAddPurchasesForm()

    return render(request, 'shop/Shop-buy.html', {'product': product, 'form': form})
```

Ключевые моменты из данного алгоритма:
•	С помощью функции get_object_or_404 получаем экземпляр товара, который добавляется в корзину.
•	Производится проверка на валидность формы
•	Производится проверка на существование аккаунта с данным user_id
•	Производится проверка на существовании корзину у пользователя. Если корзины у пользователя существует, то получаем экземпляр этой корзины с помощью метода objects.get, создаётся экземпляр Заказа (p = Purchases()), заполняется данный экземпляр данными из формы с методом POST, также присваивается к полю p.order экземпляр класса Order, который до этого получили и сохраняем данные функцией p.save(), и перенаправляем к обработчику ‘cart’ с переменной user_id. Если же корзина не существует, то вызываем функцию o = ord_creat(account), который создаёт экземпляр корзины и возвращает его, а его параметром является экземпляр класса Account текущего пользователя. Реализация приведена ниже:

```
def ord_creat(user):
    o = Orders()
    o.account = user
    o.status = False
    o.save()
    return o
Далее происходят те же действия, что были описаны выше.
Примером вывода данным будет следующий обработчик:
def matches(request):
    matchs = Matches.objects.filter(Q(home_team__q_we=True) | Q(away_team__q_we=True)).order_by('-date')

    return render(request, 'main/Match.html', {'matches': matchs})
```

В данном обработчике происходит получение списка матчей с фильтрами на то, что в сыгранном матче участвует команда Аегис, и по дате с более новых матчей. После чего данный список отправляется в контекст html, где потом с помощью цикла шаблонизатора перебираются данные о матчах. Цикл приведён ниже:

```
{% for m in matches %}
	...
{% endfor %}
```

1.3.	 Разработка интерфейса взаимодействия пользователя с системой
	Взаимодействие пользователя с системой будет производиться с помощью использования веб интерфейса.
	Основным элементом графического интерфейса сайта, использующего инструменты html, css, javascript, является html страница. На сайте элементами управления являются: элементы для перехода по ссылке на другую страницу сайта, элементы для отправки формы на сервер, элемент для прокрутки страницы в исходное расположение и т.д.
	Обычно сайты имеют 3 основных блока: header, body(main), footer. В разработанном сайте имеются все 3 блока. Блоки header и footer являются одинаковыми для всех страниц сайта, не включая страниц регистрации и авторизации.
	В блоке header находятся основная навигация сайта, в котором расположены следующие категории: Главная, Матчи, Таблица, Магазин, группа категорий «Клуб» (Состав команды, Достижение, История), также в зависимости от состояния пользователя сайта (авторизован ли он?). Если пользователь не авторизован, то в правой части header будет расположена кнопка «Вход», при нажатии которой пользователь может либо войти на сайт с помощью почты и пароля, либо зарегистрироваться на сайте используя свою почту. Если пользователь авторизован, то вместо кнопки пойти будет располагаться строка с выпадающими полями, которая будет являться почтой авторизованного пользователя, а выпадающими полями являются «Корзина» и «Выйти». При нажатии на поле «Корзина» пользователя перекинет на соответствующую страницу, где будут отображаться список выбранных товаров из магазина. Поле «Выход» отвечает за выход пользователя из учётной записи.
 
![image](https://user-images.githubusercontent.com/106113300/205445448-a7274aba-e6d6-4222-a5ea-d09d77e70701.png)
 
Рисунок 3.1 – Header сайта
	В блоке footer присутствуют 2 элемента взаимодействия: логотипы клуба и ВК. При нажатии на логотип клуба текущее положение пользователя возвращается в исходное положение. При нажатии на логотип ВК пользователя перекидывает на сообщество клуба в ВК.
 
![image](https://user-images.githubusercontent.com/106113300/205445455-fa3a7d88-94fc-4c52-8c37-90be3cc7dfaf.png)

Рисунок 3.2 – Footer сайта

В блоке main находится основной контент сайт, который отличается в каждой странице. Ниже приведены основные страницы, в которых пользователь может взаимодействовать, и их содержание:
•	«Главная»: расположены ссылки на основателей команды, “карусель” с ссылками на магазин и группу в ВК.
•	«Вход»: расположены 2 поля email и пароль.
•	«Регистрация»: имеются 3 поля email, пароль и подтверждение пароля.
•	«Состав команды»: находится список игроков команды с привязанными ссылками к их профилю в ВК.
•	«Матчи»: перечислены матчи команды с ссылками на пост определённого матча.
•	«Магазин»: расположен список товаров и фильтр на категории. Данные товары можно добавить в корзину.

**Comment by JohnBlec** [comment]
[Проектно-конструкторская часть.docx](https://github.com/JohnBlec/website-fc/files/10146630/-.docx)
*как-то странно отображается в GitHub, так что лучше в ворде посмотреть*


Хотелось бы посоветоваться насчёт оформления и содержимым в каждом пункте.
Если поконкретнее:
1. правильно ли я +- 1.1 сделал и какой из них лучше (может какой-то симбиоз сделать)
2. Правильно ли я понял 1.2 и 1.3?
3. Если в 1.3 я правильно понял, то стоит ли мне описывать каждую страницу, где используется бд. Или как-то иначе это всё расписывать

**Comment by wldmr-key** [comment]
>  Так же для упрощения структуры будет полезно разбить проект на приложения: main и shop. Приложение shop будет реализовывать функционал магазина на сайте, а main – остальную часть проекта.
(я предполагаю, это скорее относиться к архитектуре или нормально?)

это относится к архитектуре, но, если ты ограничиваешься одним предложением, то можно и здесь оставить )

>  для админки Django

ох... административной панели! Ты ж не для меня пишешь, а для вечности ))

> Правильно ли я понял 1.2 и 1.3?

вполне. А куда у тебя логическая схема БД затесалась? Ссылка на физическую реализацию? Описание твоих терзаний с view?

> Если в 1.3 я правильно понял, то стоит ли мне описывать каждую страницу, где используется бд. Или как-то иначе это всё расписывать

соврешенно необязательно. Достаточно сделать их перечисление и при необходимости кратко описать их особенности

**Comment by JohnBlec** [comment]
Под ссылкой на физ. реализацию подразумевается ссылка на приложение к моей физ. схеме?

Про описание своих "терзаний" не особо понял)
Вы имеете ввиду view в Postgres? Или в Django?
(Подозреваю, что первое, но лучше удостоверюсь)

Если первое, то мне нужно каждый мини-таблицы описать (кол-во игр, победы, ничьи и т.д.)?
Не слишком подробно описывать WHERE к каждой таблице. И если я, как раз, на досуге подумаю, как сделать проще через CASE, то нужно ли мне его описывать? Или оставить как было изначально, потом если нужно, то расскажу о таком варианте на защите?

Просто если мне нужно переделать под более эффективный вариант запрос, тогда мне нужно будет его описывать вместо предыдущего запроса.

**Comment by wldmr-key** [comment]
ну да ссылка на приложение должна где-то появиться в тексте. Например, в разделе "Реализация базы данных" или "Физическаяч схема БД".

И первое, и второе
Для БД так подробно можно не расписывать. Достаточно сказать, что текущая таблица турнира представляет собой агрегирование по результатам матчей. Поэтому, целесообразно реализовать ее в форме представления и обращаться в приложении как к таблице. Но в джанге с этим не все так просто, поэтому ...

А более эффективный вариант, если появится, то приложится ))

**Comment by JohnBlec** [comment]
Завершил описание запросов в 1.2. Разработка и реализация структуры базы данных
