### ISSUE TITLE
Проектно-технологическая часть

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#13]
1.	Проектно-технологическая часть

1.1.	Тестирование и отладка макета рабочей программы
  	Ниже, в Таблице 4.1 приведены результаты тестирования работы готового приложения.
Таблица 4.1 – Тест-кейсы

Таблица 4.1 – Продолжение

Таблица 4.1 – Продолжение

1.2.	 Развёртывание данного проекта на хостинг
Для того, чтобы выложить проект в общий доступ, нужно выбрать хостинг, на котором будет развёртываться сайт. В качестве примера хостинга будет beget.

Для начала нужно выбрать тарифный план. После выбора необходимо пройти регистрацию. Когда прошли регистрацию и вошли в систему, переходим во вкладку FTP, чтобы включить SSH-доступ, чтобы использовать SSH-клиент PuTTY для удалённого подключения к хостингу.

Устанавливаем PuTTY, запускаем его и в поле Host Name (or IP address) вставляем имя домена, который расположен на хостинге во вкладке «Управление сайтами». Появится окно, в котором нужно вписать логин и пароль, они в свою очередь пришли на почту при регистрации. После входа в систему необходимо провести следующие действия в PuTTY:

1.	Установить версию языка Python 3.10.7.
2.	Настроить виртуально окружение.
3.	Установить в виртуальном окружении версию фреймворка Django 4.1.2.

Подробности выполнения этих шагов находятся также на сайте beget (https://beget.com/ru/kb/how-to/web-apps/python). После выполнения всех операций с помощью FTP-клиента выполняется настройка зависимостей для активации Django для сайта. После чего в PuTTY совершаем миграцию, результат которого отображается на сайте хостинга во вкладке Базы данных, в котором отображены созданные таблицы на основе проекта, но они без данных. Для переноса данных из компьютера на сайт необходимо сделать бэкап данных в формате json, после чего перенести данный файл на сервер с помощью FTP-клиента и командой в PuTTY загрузить БД на хостинг. Подробнее расписано на сайте The Bosha. Ссылка расположена ниже:
https://the-bosha.ru/2016/06/29/django-delaem-damp-bazy-dannykh-i-vosstanavlivaem-iz-nego-s-dumpdata-i-loaddata/

**Comment by JohnBlec** [comment]
[Проектно-технологическая часть.docx](https://github.com/JohnBlec/website-fc/files/10146738/-.docx)

В GitHub нельзя таблицы вставить и потом страница ложиться(

Если спрашивать про таблицу тестов, то правильно ли я делаю и продолжать ли мне делать? (Так как я ещё тесты на страницы своего магазина не прописал)

Вопросы про следующие пункты, конкретно:
Пункт: Разработка руководства пользователя и руководства программиста (администратора).
    Нужен ли он и все вытекающие из этого пункта?
То что в них написано, это с прошлой курсавой.

**Comment by JohnBlec** [comment]
Конечно это не по теме к данному вопросу, но ради него создавать отдельный Issue не хочется.

В заключении что нужно написать?
То, смог ли я выполнить поставленные цели и задачи и может быть написать планах развития проекта?

Список литературы:
Нужно ли мне указывать видео/плей-листы, которыми я пользовался, когда я искал информацию, или не нужно?
А если брать ссылки сайтов которыми я пользовался, то лучше обобщённую ссылку взять? То есть https://docs.djangoproject.com/en/4.1/ вместо более конкретных ссылок на определённые возможности. Например: https://docs.djangoproject.com/en/4.1/topics/db/models/

**Comment by wldmr-key** [comment]
> Если спрашивать про таблицу тестов, то правильно ли я делаю и продолжать ли мне делать? (Так как я ещё тесты на страницы своего магазина не прописал)

пойдет

> Вопросы про следующие пункты, конкретно:
Пункт: Разработка руководства пользователя и руководства программиста (администратора).
Нужен ли он и все вытекающие из этого пункта?

я бы советовал лучше написать про развертывание твоего приложения

> Конечно это не по теме к данному вопросу, но ради него создавать отдельный Issue не хочется.

да, согласен, это значительно тяжелее, чем написать для этого специальный дисклеймер )

> В заключении что нужно написать?
То, смог ли я выполнить поставленные цели и задачи и может быть написать планах развития проекта?

вполне

> А если брать ссылки сайтов которыми я пользовался, то лучше обобщённую ссылку взять?

проще обобщенную

**Comment by JohnBlec** [comment]
> я бы советовал лучше написать про развертывание твоего приложения

Это про развёртывание на хостинг для сайтов?

И спасибо за ответы на вопросы)

**Comment by wldmr-key** [comment]
если на хостинг, то что должно быть на хостинге. Если на сервер, то что должно быть на сервере ))

**Comment by JohnBlec** [comment]
Насчёт развёртывания сайта.
Мне нужно написать, как теоретически я развёртывал свой проект на хостинг или мне надо это ещё и сделать?
Если ещё на практике делать, то это нужно выбирать хостинг с бесплатным периодом.

А то пока платить не хочется. Это нужно рассматривать множество хостингов, чтобы выбрать подходящий как в цене так и в качестве.

Может быть это глупый вопрос.
Как это развернуть на сервере? Я не особо понял

**Comment by wldmr-key** [comment]
разумеется теоретически

**Comment by JohnBlec** [comment]
Пойдёт такое описание развёртывание проекта на хостинг?

**Comment by wldmr-key** [comment]
такое - какое?

**Comment by JohnBlec** [comment]
> 1.2. Развёртывание данного проекта на хостинг
Для того, чтобы выложить проект в общий доступ, нужно выбрать хостинг, на котором будет развёртываться сайт. В качестве примера хостинга будет beget.

Я изменил текст в вопросе. 

------------------------------------------------------


1.2. Развёртывание данного проекта на хостинг
Для того, чтобы выложить проект в общий доступ, нужно выбрать хостинг, на котором будет развёртываться сайт. В качестве примера хостинга будет beget.
Для начала нужно выбрать тарифный план. После выбора необходимо пройти регистрацию. Когда прошли регистрацию и вошли в систему, переходим во вкладку FTP, чтобы включить SSH-доступ, чтобы использовать SSH-клиент PuTTY для удалённого подключения к хостингу.
Устанавливаем PuTTY, запускаем его и в поле Host Name (or IP address) вставляем имя домена, который расположен на хостинге во вкладке «Управление сайтами». Появится окно, в котором нужно вписать логин и пароль, они в свою очередь пришли на почту при регистрации. После входа в систему необходимо провести следующие действия в PuTTY:

Установить версию языка Python, которая использовалась в проекте.
Настроить виртуально окружение.
Установить в виртуальном окружении ту версию фреймворка Django, которую использовали в проекте.
Подробности выполнения этих шагов находятся также на сайте beget (https://beget.com/ru/kb/how-to/web-apps/python). После выполнения всех операций с помощью FTP-клиента выполняется настройка зависимостей для активации Django для сайта. После чего в PuTTY совершаем миграцию, результат которого отображается на сайте хостинга во вкладке MySQL, в котором отображены созданные таблицы на основе проекта, но они без данных. Для переноса данных из компьютера на сайт необходимо сделать бэкап данных в формате json, после чего перенести данный файл на сервер с помощью FTP-клиента и командой в PuTTY загрузить БД на хостинг. Подробнее расписано на сайте The Bosha. Ссылка расположена ниже:
https://the-bosha.ru/2016/06/29/django-delaem-damp-bazy-dannykh-i-vosstanavlivaem-iz-nego-s-dumpdata-i-loaddata/

**Comment by wldmr-key** [comment]
MySQL?
Лучше никак, чем так. Внимательнее читай, что пишешь и описывай конкретные шаги
"ту версию джанги, которую использовали в проекте" - это ты к кому обращаешься? к читателям пояснительной записки?

**Comment by JohnBlec** [comment]
Исправил недочёты.

> 1. Установить версию языка Python 3.10.7.
    2. Настроить виртуально окружение.
    3. Установить в виртуальном окружении версию фреймворка Django 4.1.2.
