### ISSUE TITLE
Запрос в Postgres для view

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#14]
```
CREATE OR REPLACE VIEW t_tournament AS
SELECT DISTINCT
row_number() OVER() AS id,
me.name,
COUNT(CASE WHEN (ma.home_team_id = me.id or ma.away_team_id = me.id) and tab.id = ma.table_id THEN 1
	 	   ELSE 0
	  END) AS games,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS wins,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS draws,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS loses, 
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN ma.home_goals
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN ma.away_goals
	  		   	  ELSE 0
	 		 END),0) AS goal_for,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN ma.away_goals
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN ma.home_goals
	  		   	  ELSE NULL
	 		 END),0) AS goal_against,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN COALESCE(ma.home_goals,0)-COALESCE(ma.away_goals,0)
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN COALESCE(ma.away_goals,0)-COALESCE(ma.home_goals,0)
	  		   	  ELSE NULL
	 		 END),0) AS goal_difference,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 3
			  		WHEN ma.away_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 3
			   		WHEN ma.home_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS pts,
ma.table_id, me.q_we
FROM main_members as me, main_matches as ma, main_tables as tab
WHERE (me.id = ma.home_team_id or me.id = ma.away_team_id) and tab.id = ma.table_id
GROUP BY me.name, ma.table_id, me.q_we
ORDER BY ma.table_id ASC, pts DESC, goal_difference DESC
```

**Comment by JohnBlec** [comment]
Вот результат данного запроса:
![image](https://user-images.githubusercontent.com/106113300/205497313-2b768f92-f313-4807-b65e-968f9c0fefee.png)

Результат предыдущего запроса:
![image](https://user-images.githubusercontent.com/106113300/205497377-b31adeb4-d1e5-445d-8a9b-028bcf79ab84.png)

**Comment by JohnBlec** [comment]
Правильно ли я сделал?

Если правильно, то нужно ли мне менять физ. модель и по новой привязывать к сайту эту таблицу?
Или всё-таки главное, что я знаю как сделать эффективнее запрос?

**Comment by wldmr-key** [comment]
менять необязательно. Главное, что ты знаешь. Я бы из эстетических соображений сделал запрос с WITH, чтобы не повторять одно и то же. Эффектно будет представить два графических представления плана выполнения запроса - до и после

**Comment by JohnBlec** [comment]
> Эффектно будет представить два графических представления плана выполнения запроса - до и после

Не особо понял.
И насчёт графической части, нужна ли она для бд?
Я почитал методичку и там написано что там:
![image](https://user-images.githubusercontent.com/106113300/205644757-7dc624f2-fdd6-48d2-ada1-9dbef1e46597.png)

Что тогда из проекта мне туда вставить? 
С Архитектурой понятно - там UML диаграмма по взаимодействию пользователя с сайтом
Хотя я посмотрел на UML диаграммы и их много(

![image](https://user-images.githubusercontent.com/106113300/205699933-d4cc3322-0743-450b-b793-58f0b0527609.png)

И в ЭОСе не уточняется про то, какой именно сделать, не все же 8?
![image](https://user-images.githubusercontent.com/106113300/205700177-f7a9523e-e749-4824-9041-e4e45d194af3.png)
(это я в интернете нашёл какие UML диаграммы есть)

Извините, что не по конкретно этой курсовой вопросы

**Comment by wldmr-key** [comment]
про графическое представление - https://access.crunchydata.com/documentation/pgadmin4/3.2/query_tool.html ищешь по  контексту Use the Explain tab to view a graphical representation of a query:
кстати, красивая картинка и для плаката

для БД очевидная графическая часть - логическая схема

UML - тот, что считаешь подходящим. Можно вообще не ))

**Comment by JohnBlec** [comment]
Изначальный запрос:
![table_tournaments](https://user-images.githubusercontent.com/106113300/205719807-d276fa9f-f6ca-4108-b43e-427de343163b.svg)


Оптимизированный запрос:
![t_tournament](https://user-images.githubusercontent.com/106113300/205720003-ea06547e-9ed0-4e1f-8d5e-acbc7b654985.svg)

**Comment by JohnBlec** [comment]
Ох ох ох... Мой изначальный запрос это что-то страшное...
Не представляю, где такое я могу распечатать, чтобы ещё было хоть что-то видно.

**Comment by wldmr-key** [comment]
как раз для А3 ))
а че? По-моему очень эффектно получилось
