### ISSUE TITLE
Заключение + Список литературы + Приложение

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#15]
**Заключение**

В ходе выполнения данной курсовой работы были решены задачи и была достигнута цель проекта. Была разработана система, реализующая функции:
•	Отправка данных в БД
•	Обработка данных
•	Извлечение данных из БД

В будущем проект будет развиваться, будут появляться новые функции и будут исправлены недочёты внешнего вида, безопасности и некоторые реализации алгоритмов. В частности:
•	Добавление списка бомбардиров команды
•	Подробная информация об игроке команды
•	Улучшение в навигации по матчам и турнирным таблицам
•	Проработка страниц «История», «Достижения»
•	Добавление новостной ленты на главной странице
 
**Список литературы**

1. Шнырёв, С.Л.  Базы данных: учебное пособие для вузов - М.: НИЯУ МИФИ, 2011. — 224 с. — Режим доступа: http://e.lanbook.com/book/75809 
2. Ревунков, Г.И. Базы и банки данных - М.: МГТУ им. Н.Э. Баумана, 2011. — 68 с. — Режим доступа: http://e.lanbook.com/book/52425 
3. Ревунков, Г.И. Проектирование баз данных - М.: МГТУ им. Н.Э. Баумана, 2009. — 20 с. — Режим доступа: http://e.lanbook.com/book/52390 
4. Кудрявцев, К.Я.  Создание баз данных: учебное пособие — М.: НИЯУ МИФИ, 2010. — 155 с. — Режим доступа: http://e.lanbook.com/book/75822 
5. Сидоров В.Н., Сломинская Е.Н., Полникова Т.В., Макарова О.Ю. Оформление графической части выпускной квалификационной работы. Учебное пособие. М.: МГТУ им. Н.Э. Баумана, 2016.
6. Руководство по веб-фреймворку Django [Электронный ресурс]. – URL: https://metanit.com/python/django/
7. Django Documentation [Электронный ресурс]. – URL: https://docs.djangoproject.com/en/4.1/
8. Первое знакомство с Django [Электронный ресурс]. – URL: https://proproprogs.ru/django
9. Уроки Django [Электронный ресурс]. – URL: https://itproger.com/course/django
10.	Ответы на вопрос по Django [Электронный ресурс]. – URL: https://django.fun/ru/qa/
 
**Приложение 1**

```
CREATE OR REPLACE VIEW table_tournaments AS
WITH games as (
	SELECT DISTINCT me.name, COUNT(*) as count_games, ma.table_id as table_id, me.q_we
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE (ma.home_team_id = me.id or ma.away_team_id = me.id) and tab.id = ma.table_id
	GROUP BY me.name, ma.table_id, me.q_we
),
wins as (
	SELECT DISTINCT me.name, COUNT(*) as count_wins, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ((ma.home_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id)
	OR (ma.away_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id))	
	GROUP BY me.name, ma.table_id
),
draws as (
	SELECT DISTINCT me.name, COUNT(*) as count_draws, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ((ma.home_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id)
	OR (ma.away_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id))	
	GROUP BY me.name, ma.table_id
),
loses as (
	SELECT DISTINCT me.name, COUNT(*) as count_loses, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ((ma.home_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id)
	OR (ma.away_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id))	
	GROUP BY me.name, ma.table_id
),
goal_for_home as (
	SELECT DISTINCT me.name, COALESCE(SUM(home_goals),0) as count_goal_for_h, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ma.home_team_id = me.id AND tab.id = ma.table_id
	GROUP BY me.name, ma.table_id
),
goal_for_away as (
	SELECT DISTINCT me.name, COALESCE(SUM(away_goals),0) as count_goal_for_a, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ma.away_team_id = me.id AND tab.id = ma.table_id
	GROUP BY me.name, ma.table_id
),
goal_against_home as (
	SELECT DISTINCT me.name, COALESCE(SUM(away_goals),0) as count_goal_against_h, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ma.home_team_id = me.id AND tab.id = ma.table_id
	GROUP BY me.name, ma.table_id
),
goal_against_away as (
	SELECT DISTINCT me.name, COALESCE(SUM(home_goals),0) as count_goal_against_a, ma.table_id as table_id
	FROM main_members AS me, main_matches AS ma, main_tables as tab
	WHERE ma.away_team_id = me.id AND tab.id = ma.table_id
	GROUP BY me.name, ma.table_id
)
SELECT DISTINCT
row_number() OVER() as id,
g.name,
g.count_games,
COALESCE(w.count_wins,0) as wins,
COALESCE(d.count_draws,0) as draws,
COALESCE(l.count_loses,0) as loses, 
COALESCE(gfh.count_goal_for_h,0)+COALESCE(gfa.count_goal_for_a,0) as goal_for,
COALESCE(gah.count_goal_against_h,0)+COALESCE(gaa.count_goal_against_a,0) as goal_against,
(COALESCE(gfh.count_goal_for_h,0)+COALESCE(gfa.count_goal_for_a,0))-
(COALESCE(gah.count_goal_against_h,0)+COALESCE(gaa.count_goal_against_a,0)) as goal_difference,
COALESCE(w.count_wins,0)*3+COALESCE(d.count_draws,0) as pts,
g.table_id, g.q_we
FROM games as g
left join wins as w USING (name, table_id)
left join draws as d USING (name, table_id)
left join loses as l USING (name, table_id)
left join goal_for_home as gfh USING (name, table_id)
left join goal_for_away as gfa USING (name, table_id)
left join goal_against_home as gah USING (name, table_id)
left join goal_against_away as gaa USING (name, table_id)
ORDER BY g.table_id ASC, pts DESC, goal_difference DESC
```

Запрос 1 – Представление турнирной таблицы

```
CREATE OR REPLACE VIEW t_tournament AS
SELECT DISTINCT
row_number() OVER() AS id,
me.name,
COUNT(CASE WHEN (ma.home_team_id = me.id or ma.away_team_id = me.id) and tab.id = ma.table_id THEN 1
	 	   ELSE 0
	  END) AS games,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS wins,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS draws,
COALESCE(COUNT(CASE WHEN ma.home_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS loses, 
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN ma.home_goals
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN ma.away_goals
	  		   	  ELSE 0
	 		 END),0) AS goal_for,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN ma.away_goals
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN ma.home_goals
	  		   	  ELSE NULL
	 		 END),0) AS goal_against,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id AND tab.id = ma.table_id THEN COALESCE(ma.home_goals,0)-COALESCE(ma.away_goals,0)
			  	  WHEN ma.away_team_id = me.id AND tab.id = ma.table_id THEN COALESCE(ma.away_goals,0)-COALESCE(ma.home_goals,0)
	  		   	  ELSE NULL
	 		 END),0) AS goal_difference,
COALESCE(SUM(CASE WHEN ma.home_team_id = me.id and ma.home_goals>ma.away_goals and tab.id = ma.table_id THEN 3
			  		WHEN ma.away_team_id = me.id and ma.home_goals<ma.away_goals and tab.id = ma.table_id THEN 3
			   		WHEN ma.home_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
			  		WHEN ma.away_team_id = me.id and ma.home_goals=ma.away_goals and tab.id = ma.table_id THEN 1
	  		   		ELSE NULL
	 		   END),0) AS pts,
ma.table_id, me.q_we
FROM main_members as me, main_matches as ma, main_tables as tab
WHERE (me.id = ma.home_team_id or me.id = ma.away_team_id) and tab.id = ma.table_id
GROUP BY me.name, ma.table_id, me.q_we
ORDER BY ma.table_id ASC, pts DESC, goal_difference DESC
```

Запрос 2 – Оптимизированное представление турнирной таблицы

**Comment by JohnBlec** [comment]
У меня появился "маленький" вопрос.

Я вот начал пытаться переделывать документацию под курсовую по Архитектуре, и я немного в замешательстве.

- В ТЗ особо ничего не изменишь вроде всё нужно, а если и добавлять, то не знаю что
- В Исследовательской части тоже самое, но если только такой вариант, как опустить Концептуальную схему
- В Конструкторской части.
  В 1.2 нужно описать какие файлы в Django присутствуют и для чего они используются? А в частности те файлы, которые я использовал (например, urls.py, view.py, tags). Также работу со статическими файлами и т.п.
  В 1.3 тут уже описать, например, кастомные тэги... ну и как-то идей нет.
  В 1.4 по сути тоже самое остаётся?
- В Технологической части тесты такие же будут? И что можно написать вместо развёртывания на хостинг или он тоже подойдёт к Архитектуре?
- Заключение вроде остаётся тем же

**Comment by wldmr-key** [comment]
лайфхак - если картинки, таблицы и названия разделов будут чуть другими, то никто ничего не заметит ))

**Comment by wldmr-key** [comment]
список литературы - проверь не нужно ли там чего обязательно включать я не помню

**Comment by JohnBlec** [comment]
Добавил оптимизированный запрос и добавил список литературы.
Литературу взял из методических материалов по БД (из ЭОСа). Такие подойдут?

**Comment by wldmr-key** [comment]
угу

**Comment by JohnBlec** [comment]
![table_tournaments](https://user-images.githubusercontent.com/106113300/205988584-42b6b811-443d-4f3e-b7bc-c709aef189ed.svg)
![t_tournament](https://user-images.githubusercontent.com/106113300/205988588-f8da5011-6245-4cd5-aeb9-ea33e024ec0a.svg)

**Comment by wldmr-key** [comment]
https://www.svgviewer.dev/svg-to-png
![svgviewer-png-output (1)](https://user-images.githubusercontent.com/12798933/205992612-0bf973e2-b371-45fd-b401-b4d53a735faa.png)
![svgviewer-png-output (2)](https://user-images.githubusercontent.com/12798933/205992629-43396a79-4568-4b3d-9342-5777f6b54259.png)

**Comment by JohnBlec** [comment]
О, спасибо большое!)
