### ISSUE TITLE
Прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#2]
Это примерный макет главной страницы сайта. Здесь будет располагаться важная информация. Например, как основатели клуба, различные акции клубного магазина и т.п. **_(Нуждается в доработке)_**

![image](https://user-images.githubusercontent.com/106113300/192160836-3c078a07-87c6-4c52-933b-8b69da7b5e4a.png)

![image](https://user-images.githubusercontent.com/106113300/192160880-7a164468-5727-41e0-867d-5847eb4899f5.png)

![image](https://user-images.githubusercontent.com/106113300/192160896-9ddb69a7-9af8-4967-ad0a-fa8113587215.png)

В разделе Клуб\Состав команды будет отображаться текущий состав команды.
**_(Нуждается в визуальной доработке: фотографии и шрифтов)_** 

![image](https://user-images.githubusercontent.com/106113300/192160908-da23a27e-e245-4e17-a591-ab19fdebec25.png)

![image](https://user-images.githubusercontent.com/106113300/192160912-762d0fa2-1d10-4559-81a4-93b30df9993a.png)

В разделе Клуб\Достижения будут отображаться трофеи команды, результат турнира и отличившиеся игроков.
(Внешний вид будет +- похож как и в ВК)

![image](https://user-images.githubusercontent.com/106113300/192160941-1dc0ecd5-0ee6-4c78-8320-842fb514d3d8.png)

В разделе Клуб\История будет отображаться история основания и развитии клуба. На данный момент написан случайный текст, который читать не нужно.
**_(Нуждается в проработке истории и возможных иллюстраций)_**

![image](https://user-images.githubusercontent.com/106113300/192160972-b58cc905-21b8-4d51-9a91-4f5095ef3bb6.png)

 
В разделе Матчи будут отображаться результаты предыдущих матчей и расписание следующих.
_**(Не нуждается в доработке)**_
 
![image](https://user-images.githubusercontent.com/106113300/192160992-846503d5-64b1-4310-9cb0-235e3d8c6b1a.png)

В разделе Таблица будут отображать таблицы текущего турнира и предыдущих.
_**(Нужно доработать отображение таблиц предыдущих сыгранных турниров)**_
 
![image](https://user-images.githubusercontent.com/106113300/192160999-437c6f3b-11bf-4015-874d-288000eefcd1.png)

В разделе Магазин будут отображаться клубный мерч.

**_(Нужно доработать стадию покупки товара)_**

1.	Внешний вид футболки.
2.	Выбор размера.
3.	Номер телефона для звонка с покупателем.
 
 
![image](https://user-images.githubusercontent.com/106113300/192161029-5c0fc2c3-dd52-4181-be75-ed4476672add.png)

![image](https://user-images.githubusercontent.com/106113300/192161042-addeaace-ab0f-479e-922d-b043497582c7.png)

**Comment by JohnBlec** [comment]
[Прототип сайта.docx](https://github.com/JohnBlec/website-fc/files/9641586/default.docx)

**Comment by wldmr-key** [comment]
норм. Опять-таки, чтобы оценить полноту скетчей нужно описание предметной области и требований к системе, но навскидку выглядит убедительно
