### ISSUE TITLE
Концептуальная модель предметной области

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#3]
![image](https://user-images.githubusercontent.com/106113300/195192428-f1d9714a-438f-48cf-bd23-dd0092bbe139.png)

Турниры и Турнирные таблицы зависят друг к другу связью «Один ко многим», так как турнир проводится не 1 раз, а несколько раз за свою историю существования (конечно, бывают исключения). Например, есть Английская Премьер-Лига и её проводят с Лета по Весну (этот период называется сезон), а когда начинается следующий сезон, то турнир, по сути, тот же самый (Логотип, название), но другой, с точки зрения времени.

Турниры таблицы и Игровые дни зависят друг к другу двумя связями «Один ко многим», так как турнира будет формироваться из результатов матчей. Если турнир только начался и игры ещё не сыгранны, то за счёт расписания будущих игр будет формироваться турнирная таблица.

Участники и Игровые дни зависят друг к другу двумя связями «Один ко многим», так как игровые дни формируются из участников, которые между собой играют, и они будут встречаться несколько раз в разных игровых днях. Атрибут у Участников «Наша ли команда?» необходима для вывода на сайте расписание с результатами игр исключительна для нашей команды.

**Comment by JohnBlec** [comment]
Если удобнее будет в Ворде посмотреть.
[Конц. модель.docx](https://github.com/JohnBlec/website-fc/files/9641585/default.docx)

**Comment by wldmr-key** [comment]
ах! разве в концептуальной модели есть первичные ключи? Вообще судить о ее правильности можно только после появления описания предметной области, где вводятся все включенные в модель понятия. Так что жду его

**Comment by wldmr-key** [comment]
будем править по результатам обсуждения в прошлый вторник? Или так оставим до декабря?

**Comment by JohnBlec** [comment]
Версия 2.0
[Конц. модель.docx](https://github.com/JohnBlec/website-fc/files/9745575/default.docx)

**Comment by wldmr-key** [comment]
рисунок, значит, сюда бросить лениво... так-так...

1) нужна ли привязка участников к турниру? Тут есть два правильных ответа, но свой следует мотивировать в описании концептуальной схемы
2) у участников есть привязка "свой-чужой"? Иначе, как ты будешь выделять свою команду? Или в хардкоде?
3) про участников хоть какая-то инфо будет?
4) зачем нужно регистрироваться на сайте? Может, хоть заказы товаров делать? Или подписки что-ли?
5) лого турнира у каждого игрового дня свое? ))

**Comment by JohnBlec** [comment]
Надеюсь, финальная версия схемы)
[Конц. модель.docx](https://github.com/JohnBlec/website-fc/files/9758841/default.docx)

**Comment by wldmr-key** [comment]
зря надеешься ))

твои товары настолько уникальны, что могут входить только в один заказ?

**Comment by JohnBlec** [comment]
Справедливое замечание)
Исправил:
[Конц. модель.docx](https://github.com/JohnBlec/website-fc/files/9759560/default.docx)

**Comment by wldmr-key** [comment]
как я говорил, раздел концептуальная модель нуждается в словесных пояснениях

**Comment by JohnBlec** [comment]
Извините, но я вроде и так написал пояснение. Или я неправильно его написал?
