### ISSUE TITLE
Анализ аналогов

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#4]
**_Анализ аналогов_**

При проектировании сайта были взяты некоторые идеи и интересные дизайнерские подходы с других подобных сайтов. 

Основные пункты футбольных сайтов, без которых сложно представить подобного рода сайт:
1.	Расписание игр
2.	Состав
3.	Текущее положение в турнире
4.	Достижения

Остальные пункты не особо важны для интересующегося футболом человека, такие как:
1.	История основания
2.	Магазин

Обосновывается это тем, что никому не интересна история основания, кроме болельщиков команды. В магазин первый попавшиеся интернет пользователь не зайдёт и не станет покупать продукт, если только форма не привлечёт его своим дизайном.

Данные элементы были взяты за основу разработки визуальной части некоторых страниц:
1.	Некоторые категории для навигации сайта у ФК Калуги. Клуб, Матчи, Магазин. https://fc-kaluga.ru/
 
![image](https://user-images.githubusercontent.com/106113300/192161310-ecff4253-e7c8-4178-b72c-798f3915bbab.png)

2.	Внешний вид состава у Реал Мадрида, так как был прост в реализации. https://www.realmadrid.com/en/football/squad

![image](https://user-images.githubusercontent.com/106113300/192161316-201b3a5d-fdc1-4779-9404-dadd628a0ad5.png)

 
3.	Расписание/результаты игр у ФК Барселоны, так как прост в реализации и привлекателен с дизайнерской точки зрения. https://www.fcbarcelona.com/en/football/first-team/results
 
![image](https://user-images.githubusercontent.com/106113300/192161321-149122be-82f8-4ddd-9343-bc84007665ce.png)

4.	Внешний вид для магазина -  у Манчестера Сити. Также прост в реализации, как и состав команды (та же механика работает по расположению элементов). https://shop.mancity.com/en/kits/#tile-701221522-black
 
![image](https://user-images.githubusercontent.com/106113300/192161328-a144be9c-ecd1-441c-83e0-7f79c6f2c44c.png)

Также планируется доработать покупку в таком же стиле как у Сити.
https://shop.mancity.com/en/manchester-city-away-jersey-2022-23/701221522-black.html
 
![image](https://user-images.githubusercontent.com/106113300/192161332-7af343fd-1a2e-4b98-b4e4-c794e0f335bc.png)

Остальные аспекты либо были реализованы самостоятельно такие, как турнирная таблица, главная страница. Либо ещё будут реализованы – история основания и достижения.

**Comment by JohnBlec** [comment]
Если есть необходимость
[Анализ аналогов.docx](https://github.com/JohnBlec/website-fc/files/9641595/default.docx)

**Comment by wldmr-key** [comment]
все отлично, но в жанре пояснительной записки следует везде убрать первое лицо ("Объясняю", "доработаю" и т.д. и всякие игривости "Теперь начнём разбирать", "позаимствовал"). Нужно сделать чуть посуше (объективней)

Все остальное - наличие ссылок и объяснений - хорошо ))

**Comment by JohnBlec** [comment]
Не знаю отображается ли то, что я отредактировал текст.
Так что напишу, что я отредактировал, надеюсь, что правильно.

**Comment by wldmr-key** [comment]
> Не знаю отображается ли то, что я отредактировал текст. Так что напишу, что я отредактировал, надеюсь, что правильно.

да отображается и видны исправления (как это видно - можешь глянуть в моем предыдущем комментарии)

Нормально, но следи за лексиконом! Фишки!!! Гики!!!
