### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#7]
**1.	Техническое задание**

**1.1.	 Общие сведения:**
**1.1.1.	 Полное наименование системы:**
Сайт футбольного клуба

**1.1.2.	 Наименования организации-заказчика, разработчика системы:**
Заказчик: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-52Б Сафин П.Р.

**1.1.3.	Плановые сроки начала и окончания работы по созданию системы:**
Плановый срок начала работ – 12 сентября 2022 года.
Плановый срок окончания работ – 1 декабря 2022 года.

**1.2.	 Назначение и цели создания системы**
**1.2.1.	Назначение системы:**
Система предназначена любителям футбола для отслеживания состояния команды и для покупки товаров клуба.
**1.2.2.	 Цели создания системы:**
Система создается для повышения узнаваемости, так как не каждый любительский клуб имеет свой личный сайт. Также для продажи футбольной атрибутики.
 
**1.3.	 Требования к системе**

**1.3.1.	 Требования к системе в целом:**
**1.3.1.1.	Требования к структуре и функционированию системы:**
Система представляет собой 4 части:
•	Клиентское приложение (веб-сайт)
•	Бизнес-логики приложения
•	Место хранения данных (база данных)
•	Хостинг

**1.3.1.2.	Требования по эргономике и технической эстетике:**
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе.
Интерфейс должен быть понятен и не перегружен графическими элементами.

**1.3.2.	 Требования к функциям (задачам), выполняемым системой**

-	Авторизация.
-	Адекватное отображение контента (Текстов, изображений) на мобильных устройствах и ПК
-	Занесение новый данных в БД
-	Вывод данных на сайт из БД
-	Покупка атрибутики.

**1.3.3.	 Требования к видам обеспечения**

**1.3.3.1.	Требования к лингвистическому обеспечению системы**

Средством описания предметной области, также, как и средством взаимодействия пользователя с системой является русский.

**1.3.3.2.	Требования к входным и выходным данным**

Входными данными системы от пользователей браузера являются email и пароль, а от модераторов сайта – состав команды, турнирная таблица, товаров, расписание и т.д. Выходными данными является вся информация о клубе. 

**1.3.3.3.	Требования к программному обеспечению системы**

В качестве языка программирования для разработки северной части сайта используется Python Django, в качестве СУБД будет Postgres, а для создания пользовательского интерфейса используется HTML и CSS.
Обязательное требование – наличие браузера.

**1.4.	 Состав и содержание работ по созданию (развитию) системы**

1.	Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса (1 – 4-я недели).

2.	Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД (5 – 7-я недели).

3.	Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и откладка приложения. Разработка эксплуатационной документации. (8 – 10-я недели).

4.	Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы (11 – 14-я недели).

**1.5.	 Порядок контроля и приемки системы**

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.

**1.6.	 Требования к документированию**
Требуется предоставить:
1.	Техническое задание в соответствии с ГОСТ 34.602-89
2.	Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by JohnBlec** [comment]
К сожалению, я не всё вспомнил, что мне нужно было исправить. Единственное, что помню и не знаю как исправить это 1.3.1.1. и 1.3.2. А всё что вспомнил, исправил.

**Comment by wldmr-key** [comment]
"продажы " !!!!!!!!!!!!!!!!!!!!!!!!!!!!

1.3.1.1 и 1.3.2 - это одно и то же. Не находишь? Так делать не нужно

Структура - это как построена твоя система. Для функционироания системы, как я понимаю, нужны хостинг и постоянное управление контентом

функции просмотра (1.3.2) стоило расписать поподробнее, так как контент нигде не конкретизируется

а, в общем, норм

**Comment by JohnBlec** [comment]
Исправил недочёты.

**Comment by JohnBlec** [comment]
Решил подправить ТЗ.
Как минимум я не на C# пишу свой проект)

**Comment by wldmr-key** [comment]
это правильно
