### ISSUE TITLE
Логическая схема БД

### ISSUE THREAD

**Issue by JohnBlec** [JohnBlec/website-fc#9]
![image](https://user-images.githubusercontent.com/106113300/197820571-bca3d511-cac8-4215-9ca4-f115646f441e.png)

**Comment by wldmr-key** [comment]
я правильно понимаю, что игровой номер может совпадать у разных игроков, судя по твоим ключам?

У игровых дней отсутствует внешний ключ к турнирным таблицам (прикинь, целесообразны ли здесь естественные ключи)

У покупок отсутствует внешний ключ к заказам

**Comment by JohnBlec** [comment]
Исправил
[Лог. модель.docx](https://github.com/JohnBlec/website-fc/files/9861884/default.docx)
